Repository p-ser/p-ser-backend, pull requests merged in 2024-06, with the labels that each got.

#41 [KSP-254] Review Service 생성
  src/main/java/com/pser/hotel/domain/hotel/application/ReviewService.java
  src/main/java/com/pser/hotel/domain/hotel/domain/ReviewImage.java
  src/main/java/com/pser/hotel/domain/hotel/dto/ReviewDto.java
Labels: 서비스

#44 [KSP-260] 커서 기반 페이지네이션 리팩토링
  src/main/java/com/pser/hotel/domain/hotel/dao/HotelDaoImpl.java
  src/main/java/com/pser/hotel/domain/hotel/domain/HotelCategoryEnum.java
  src/main/java/com/pser/hotel/domain/hotel/dto/request/HotelSearchRequest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/HotelDaoImplTest.java
Labels: 리팩토링

#45 [KSP-264] hotel mapstruct 누락 매핑 타겟 리팩토링
  src/main/java/com/pser/hotel/domain/hotel/dto/mapper/HotelMapper.java
Labels: 리팩토링

#50 [KSP 274] Review Api 리펙토링
  src/main/java/com/pser/hotel/domain/hotel/api/ReviewApi.java
  src/main/java/com/pser/hotel/domain/hotel/application/ReviewService.java
  src/main/java/com/pser/hotel/domain/hotel/dao/ReviewDao.java
  src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
  src/main/java/com/pser/hotel/domain/hotel/dto/request/ReviewSearchRequest.java
Labels: 리팩토링

#52 [KSP-272] 객실 Response DTO 수정
  src/main/java/com/pser/hotel/domain/hotel/api/RoomApi.java
  src/main/java/com/pser/hotel/domain/hotel/api/RoomRestApi.java
  src/main/java/com/pser/hotel/domain/hotel/application/RoomService.java
  src/main/java/com/pser/hotel/domain/hotel/dao/RoomDao.java
  src/main/java/com/pser/hotel/domain/hotel/dao/RoomDaoCustom.java
  src/main/java/com/pser/hotel/domain/hotel/dao/RoomDaoImpl.java
  src/main/java/com/pser/hotel/domain/hotel/domain/Room.java
  src/main/java/com/pser/hotel/domain/hotel/domain/RoomImage.java
  src/main/java/com/pser/hotel/domain/hotel/dto/mapper/RoomMapper.java
  src/main/java/com/pser/hotel/domain/hotel/dto/request/RoomRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/response/RoomDetailResponse.java
  src/main/java/com/pser/hotel/domain/hotel/dto/response/RoomListResponse.java
  src/main/java/com/pser/hotel/domain/hotel/dto/response/RoomResponse.java
  src/main/java/com/pser/hotel/global/config/MethodAuthorizationManager.java
  src/test/java/com/pser/hotel/domain/hotel/api/RoomApiTest.java
  src/test/java/com/pser/hotel/domain/hotel/api/RoomPreAuthorizeTest.java
  src/test/java/com/pser/hotel/domain/hotel/api/RoomRestApiTest.java
  src/test/java/com/pser/hotel/domain/hotel/application/RoomServiceTest.java
  src/test/java/com/pser/hotel/domain/hotel/config/MapperConfig.java
  src/test/java/com/pser/hotel/domain/hotel/dao/PerformanceTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/RoomDaoImplTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/RoomImageTest.java
  src/test/java/com/pser/hotel/domain/hotel/dto/RoomMapperTest.java
  src/test/java/com/pser/hotel/domain/hotel/util/Utils.java
Labels: 리팩토링

#54 [KSP-272] 객실 조회 관련 Response 리팩토링
  src/main/java/com/pser/hotel/domain/hotel/api/RoomApi.java
  src/main/java/com/pser/hotel/domain/hotel/api/RoomRestApi.java
  src/main/java/com/pser/hotel/domain/hotel/application/RoomService.java
  src/main/java/com/pser/hotel/domain/hotel/dao/RoomDao.java
  src/main/java/com/pser/hotel/domain/hotel/dto/mapper/RoomMapper.java
  src/main/java/com/pser/hotel/domain/hotel/dto/response/RoomDetailResponse.java
  src/test/java/com/pser/hotel/domain/hotel/api/RoomApiTest.java
  src/test/java/com/pser/hotel/domain/hotel/api/RoomRestApiTest.java
  src/test/java/com/pser/hotel/domain/hotel/application/RoomServiceTest.java
Labels: 리팩토링

#55 [KSP 290] Review Api 리펙토링 및 기능추가
  src/main/java/com/pser/hotel/domain/hotel/api/ReviewApi.java
  src/main/java/com/pser/hotel/domain/hotel/application/ReviewService.java
  src/main/java/com/pser/hotel/domain/hotel/dao/ReviewDao.java
  src/main/java/com/pser/hotel/domain/hotel/dao/ReviewDaoCustom.java
  src/main/java/com/pser/hotel/domain/hotel/dao/ReviewDaoImpl.java
  src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
  src/main/java/com/pser/hotel/domain/hotel/domain/Room.java
  src/main/java/com/pser/hotel/domain/hotel/dto/ReviewDto.java
  src/main/java/com/pser/hotel/domain/hotel/dto/mapper/ReviewMapper.java
  src/main/java/com/pser/hotel/domain/hotel/dto/request/ReviewCreateRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/request/ReviewSearchRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/request/ReviewUpdateRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/response/ReviewResponse.java
  src/main/java/com/pser/hotel/domain/model/GradeEnum.java
Labels: 새로운기능, 리팩토링, 컨트롤러
