Repository p-ser/p-ser-backend, pull requests merged in 2024-05, with the labels that each got.

#19 [KSP-112] ReviewController 구현
  src/main/java/com/pser/hotel/domain/hotel/api/ReviewApi.java
  src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
  src/main/java/com/pser/hotel/domain/hotel/dto/ReviewListResponseDto.java
  src/main/java/com/pser/hotel/domain/hotel/dto/ReviewRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/ReviewResponseDto.java
Labels: 컨트롤러

#20 [KSP-149] RoomImage 저장 기능 리팩토링
  src/main/java/com/pser/hotel/domain/hotel/application/RoomService.java
  src/main/java/com/pser/hotel/domain/hotel/domain/Room.java
  src/main/java/com/pser/hotel/domain/hotel/domain/RoomImage.java
  src/main/java/com/pser/hotel/domain/hotel/dto/RoomRequest.java
  src/test/java/com/pser/hotel/domain/hotel/api/RoomPreAuthorizeTest.java
  src/test/java/com/pser/hotel/domain/hotel/api/RoomRestApiTest.java
  src/test/java/com/pser/hotel/domain/hotel/application/RoomServiceTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/RoomDaoTest.java
  src/test/java/com/pser/hotel/domain/hotel/dto/RoomMapperTest.java
  src/test/java/com/pser/hotel/domain/hotel/util/Utils.java
Labels: 리팩토링, 테스트, 서비스

#24 [KSP-154] 숙소 Service 구현
  src/main/java/com/pser/hotel/domain/hotel/api/HotelApi.java
  src/main/java/com/pser/hotel/domain/hotel/application/HotelService.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelMapper.java
  src/test/java/com/pser/hotel/domain/hotel/api/HotelApiTest.java
  src/test/java/com/pser/hotel/domain/hotel/application/HotelServiceTest.java
Labels: 리팩토링, 테스트, 서비스

#23 [KSP 147] EntityImages 추가
  src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
  src/main/java/com/pser/hotel/domain/hotel/domain/ReviewImage.java
Labels: 엔티티

#27 [KSP-170] 숙소 시설(Facility) 리팩토링
  src/main/java/com/pser/hotel/domain/hotel/dao/HotelDaoImpl.java
  src/main/java/com/pser/hotel/domain/hotel/domain/Facility.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelCreateRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelMapper.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelResponse.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelSearchRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelUpdateRequest.java
  src/test/java/com/pser/hotel/domain/hotel/api/HotelApiTest.java
  src/test/java/com/pser/hotel/domain/hotel/application/HotelServiceTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/FacilityTest.java
Labels: 리팩토링, 테스트

#29 [KSP-172] 숙소 이미지 관련 기능 구현
  src/main/java/com/pser/hotel/domain/hotel/application/HotelService.java
  src/main/java/com/pser/hotel/domain/hotel/dao/FacilityDao.java
  src/main/java/com/pser/hotel/domain/hotel/dao/HotelDaoImpl.java
  src/main/java/com/pser/hotel/domain/hotel/dao/HotelImageDao.java
  src/main/java/com/pser/hotel/domain/hotel/domain/Facility.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelCreateRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelMapper.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelResponse.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelSearchRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelUpdateRequest.java
  src/test/java/com/pser/hotel/domain/hotel/api/HotelApiTest.java
  src/test/java/com/pser/hotel/domain/hotel/application/HotelServiceTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/HotelDaoImplTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/UserDaoTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/FacilityTest.java
  src/test/java/com/pser/hotel/domain/hotel/util/Utils.java
Labels: 리팩토링, 세팅

#25 [KSP-153] 예약 API 구현
  src/main/java/com/pser/hotel/domain/hotel/api/ReservationApi.java
  src/main/java/com/pser/hotel/domain/hotel/dao/ReservationDao.java
  src/main/java/com/pser/hotel/domain/hotel/dao/RoomDao.java
  src/main/java/com/pser/hotel/domain/hotel/domain/Reservation.java
  src/main/java/com/pser/hotel/domain/hotel/dto/reservation/request/ReservationSaveRequestDto.java
  src/main/java/com/pser/hotel/domain/hotel/dto/reservation/request/ReservationUpdateRequestDto.java
  src/main/java/com/pser/hotel/domain/hotel/dto/reservation/response/ReservationDeleteResponseDto.java
  src/main/java/com/pser/hotel/domain/hotel/dto/reservation/response/ReservationFindDetailResponseDto.java
  src/main/java/com/pser/hotel/domain/hotel/dto/reservation/response/ReservationFindResponseDto.java
  src/main/java/com/pser/hotel/domain/hotel/dto/reservation/response/ReservationSaveResponseDto.java
  src/main/java/com/pser/hotel/domain/hotel/dto/reservation/response/ReservationUpdateResponseDto.java
  src/main/java/com/pser/hotel/domain/hotel/service/ReservationService.java
  src/main/java/com/pser/hotel/global/util/ReservationUpdateMapper.java
  src/test/java/com/pser/hotel/domain/hotel/util/Utils.java
Labels: 새로운기능

#30 [KSP-202] 호텔 Dao 검색 테스트 코드
  src/test/java/com/pser/hotel/domain/hotel/dao/HotelSearchTest.java
  src/test/java/com/pser/hotel/domain/hotel/util/Utils.java
Labels: 리팩토링, 테스트

#34 [KSP-181] 타임특가 API 구현 및 숙소 API 리팩토링
  src/main/java/com/pser/hotel/domain/hotel/api/HotelApi.java
  src/main/java/com/pser/hotel/domain/hotel/api/TimesaleApi.java
  src/main/java/com/pser/hotel/domain/hotel/application/HotelService.java
  src/main/java/com/pser/hotel/domain/hotel/application/TimesaleService.java
  src/main/java/com/pser/hotel/domain/hotel/dao/HotelDaoCustom.java
  src/main/java/com/pser/hotel/domain/hotel/dao/HotelDaoImpl.java
  src/main/java/com/pser/hotel/domain/hotel/dao/TimesaleCustom.java
  src/main/java/com/pser/hotel/domain/hotel/dao/TimesaleDao.java
  src/main/java/com/pser/hotel/domain/hotel/dao/TimesaleDaoImpl.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelMapper.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelResponse.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelSearchRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/HotelSummaryResponse.java
  src/main/java/com/pser/hotel/domain/hotel/dto/TimesaleCreateRequest.java
  src/main/java/com/pser/hotel/domain/hotel/dto/TimesaleMapper.java
  src/main/java/com/pser/hotel/domain/hotel/dto/TimesaleRoomResponse.java
  src/main/java/com/pser/hotel/global/config/MethodAuthorizationManager.java
  src/test/java/com/pser/hotel/domain/hotel/api/TimesaleApiTest.java
  src/test/java/com/pser/hotel/domain/hotel/application/HotelServiceTest.java
  src/test/java/com/pser/hotel/domain/hotel/application/TimesaleServiceTest.java
  src/test/java/com/pser/hotel/domain/hotel/config/MapperConfig.java
  src/test/java/com/pser/hotel/domain/hotel/dao/FacilityDaoTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/HotelDaoImplTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/HotelDaoTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/HotelSearchTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/RoomDaoImplTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/RoomDaoTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/TimesaleDaoImplTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/TimesaleDaoTest.java
  src/test/java/com/pser/hotel/domain/hotel/dao/UserDaoTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/AmenityTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/FacilityTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/HotelImageTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/HotelTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/ReservationTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/RoomImageTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/RoomTest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/TimeSaleTest.java
  src/test/java/com/pser/hotel/domain/hotel/util/Utils.java
Labels: 새로운기능, 리팩토링, 테스트

#36 [KSP-207] Review DAO 기능 추가
  src/main/java/com/pser/hotel/domain/hotel/dao/ReviewDao.java
  src/main/java/com/pser/hotel/domain/hotel/dao/ReviewDaoCustom.java
  src/main/java/com/pser/hotel/domain/hotel/dao/ReviewDaoImpl.java
  src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
  src/main/java/com/pser/hotel/domain/hotel/domain/ReviewImage.java
  src/main/java/com/pser/hotel/domain/hotel/dto/request/ReviewSearchRequest.java
  src/test/java/com/pser/hotel/domain/hotel/domain/ReviewTest.java
Labels: 새로운기능
